#!/usr/bin/env python3
"""
Multi-agent research pipeline using the Claude Agent SDK.

Stages:
  1. Planner  — breaks the topic into sub-topics and writes plan.json
  2. Researcher — searches the web for each sub-topic and writes research.md
  3. Writer   — synthesises findings into a polished report.md

Usage:
  python pipeline.py "Your research topic"

Environment:
  ANTHROPIC_API_KEY   required
  WORKSPACE           directory for inter-agent state (default: ./workspace)
"""

import anyio
import json
import os
import sys
import time
from pathlib import Path

from claude_agent_sdk import (
    AssistantMessage,
    ClaudeAgentOptions,
    ResultMessage,
    SystemMessage,
    TextBlock,
    query,
)

WORKSPACE = Path(os.environ.get("WORKSPACE", "./workspace"))


# ---------------------------------------------------------------------------
# Shared tracer — prints a timeline of every assistant turn
# ---------------------------------------------------------------------------

def _trace_messages(stage: str):
    """Return an async generator that logs message activity for a pipeline stage."""
    async def _run(prompt: str, options: ClaudeAgentOptions):
        turn = 0
        t0 = time.monotonic()
        async for msg in query(prompt=prompt, options=options):
            elapsed = time.monotonic() - t0
            if isinstance(msg, SystemMessage) and msg.subtype == "init":
                print(f"  [{stage}] session={msg.data.get('session_id', '')[:8]}…")
            elif isinstance(msg, AssistantMessage):
                turn += 1
                text_blocks = [b for b in msg.content if isinstance(b, TextBlock)]
                if text_blocks:
                    preview = text_blocks[0].text[:120].replace("\n", " ")
                    print(f"  [{stage}] turn {turn} ({elapsed:.1f}s) — {preview}…")
                if msg.usage:
                    print(
                        f"  [{stage}] usage: in={msg.usage.get('input_tokens', 0)} "
                        f"out={msg.usage.get('output_tokens', 0)}"
                    )
            elif isinstance(msg, ResultMessage):
                yield msg
    return _run


# ---------------------------------------------------------------------------
# Stage 1 — Planner
# ---------------------------------------------------------------------------

async def run_planner(topic: str) -> dict:
    """Break the topic into sub-topics and write plan.json to WORKSPACE."""
    plan_path = WORKSPACE / "plan.json"

    prompt = f"""You are a research planner. Your job is to create a focused research plan for the topic below.

Topic: {topic!r}

Steps:
1. Identify 3–5 distinct sub-topics that together give a complete picture of the topic.
2. For each sub-topic write one precise research question.
3. Propose 2 specific web search queries per sub-topic that are likely to return high-quality results.
4. Write the plan as valid JSON to the file: {plan_path}

JSON schema:
{{
  "topic": "<string>",
  "subtopics": [
    {{
      "id": "<1-based int as string>",
      "title": "<short title>",
      "question": "<one sentence research question>",
      "search_queries": ["<query 1>", "<query 2>"]
    }}
  ]
}}

After writing the file, print a one-line summary of the plan.
"""

    print("\n[Stage 1] Planner starting…")
    runner = _trace_messages("planner")
    async for msg in runner(
        prompt=prompt,
        options=ClaudeAgentOptions(
            cwd=str(WORKSPACE),
            allowed_tools=["Write", "Read"],
            permission_mode="bypassPermissions",
            allow_dangerously_skip_permissions=True,
        ),
    ):
        if isinstance(msg, ResultMessage):
            print(f"  [planner] done — result: {msg.result[:100]}")

    with open(plan_path) as f:
        plan = json.load(f)
    print(f"  [planner] plan.json written ({len(plan['subtopics'])} subtopics)")
    return plan


# ---------------------------------------------------------------------------
# Stage 2 — Researcher
# ---------------------------------------------------------------------------

async def run_researcher(plan: dict) -> None:
    """Web-search each sub-topic and append findings to research.md."""
    plan_path = WORKSPACE / "plan.json"
    research_path = WORKSPACE / "research.md"

    prompt = f"""You are a research specialist with access to web search.

Read the research plan from {plan_path}.

For every sub-topic in the plan:
1. Run the suggested search queries with WebSearch.
2. Follow up with WebFetch on 1–2 of the most promising URLs.
3. Extract key facts, statistics, examples, and direct quotes.

When you have covered all sub-topics, write your findings to {research_path} in this markdown format:

---
# Research: <topic>
_Generated by researcher agent_

## <Sub-topic title>
<3–4 paragraphs of findings>

### Sources
- [Title](URL)
---

Be specific — include numbers, dates, and direct quotes where available.
"""

    print("\n[Stage 2] Researcher starting…")
    runner = _trace_messages("researcher")
    async for msg in runner(
        prompt=prompt,
        options=ClaudeAgentOptions(
            cwd=str(WORKSPACE),
            allowed_tools=["Read", "Write", "WebSearch", "WebFetch"],
            permission_mode="bypassPermissions",
            allow_dangerously_skip_permissions=True,
            max_turns=40,
        ),
    ):
        if isinstance(msg, ResultMessage):
            print(f"  [researcher] done — result: {msg.result[:100]}")

    size = research_path.stat().st_size if research_path.exists() else 0
    print(f"  [researcher] research.md written ({size} bytes)")


# ---------------------------------------------------------------------------
# Stage 3 — Writer
# ---------------------------------------------------------------------------

async def run_writer(topic: str) -> None:
    """Synthesise research.md into a polished report.md."""
    research_path = WORKSPACE / "research.md"
    report_path = WORKSPACE / "report.md"

    prompt = f"""You are a technical writer producing content for cloud-native developers.

Read the research findings from {research_path}.

Write a polished, publication-ready technical article about {topic!r}.

Requirements:
- Compelling introduction that explains *why* this topic matters right now
- Clear section headers (H2) for each major area
- Concrete examples: include short code snippets or CLI commands where relevant
- A comparison table if the topic involves evaluating multiple approaches
- "Key Takeaways" section as the final section (3–5 bullet points)
- Target length: 1 800–2 500 words
- Audience: senior engineers who are pragmatic and time-constrained

Write the final article to {report_path} in markdown format.
Do NOT include a "Sources" section — inline hyperlinks are sufficient.
"""

    print("\n[Stage 3] Writer starting…")
    runner = _trace_messages("writer")
    async for msg in runner(
        prompt=prompt,
        options=ClaudeAgentOptions(
            cwd=str(WORKSPACE),
            allowed_tools=["Read", "Write"],
            permission_mode="bypassPermissions",
            allow_dangerously_skip_permissions=True,
        ),
    ):
        if isinstance(msg, ResultMessage):
            print(f"  [writer] done — result: {msg.result[:100]}")

    size = report_path.stat().st_size if report_path.exists() else 0
    print(f"  [writer] report.md written ({size} bytes)")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

async def main() -> None:
    topic = " ".join(sys.argv[1:]) if len(sys.argv) > 1 else "eBPF for Kubernetes observability"

    WORKSPACE.mkdir(parents=True, exist_ok=True)
    print(f"Workspace: {WORKSPACE.resolve()}")
    print(f"Topic:     {topic}")
    print("=" * 60)

    t_start = time.monotonic()

    plan = await run_planner(topic)
    await run_researcher(plan)
    await run_writer(topic)

    elapsed = time.monotonic() - t_start
    report = WORKSPACE / "report.md"
    print("\n" + "=" * 60)
    print(f"Pipeline complete in {elapsed:.1f}s")
    print(f"Report: {report.resolve()}")
    if report.exists():
        print(f"Size:   {report.stat().st_size:,} bytes")


if __name__ == "__main__":
    anyio.run(main)
